"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lf%gzc^!b5t2tve1_q=2qq)ids-8k_m1*nhvvon9$n__r(f81o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

CERT = '6316dc322e44e871713ce38804a07789ae20f0c9'
KEY = 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC76eyroh2mFLQOTVxjD/ZKnWB7QexLgcjEyTfKfN2CDBSGtFgxPIsP' \
      '/uzo2VDFc4WIitPqREzVFHr5zSCroH7rHS6IrYmMH3lOTDwquMt57Y' \
      '+D85szjLwgRfgT4ObpXY1DtkgbJUfeQIK40GRPXulGyH1sm0rW5bEWIeFAKBtmgFMbvygqRCp8WVajSTBTVMY4cUtKu5ihtCiqmquHNf' \
      '+nT2FKy+7MSgYOIOed1opBEhYX/8yFUpRlrRegI/5ibsy7S7gO5JznCGrARjTuxSdYEp6CrLUs7GZ8mqYWFCb' \
      '+SICdhoJhIPUWANXCowNe2zpG3hSts+sYgwEz1LhHczFFAgMBAAECggEAZcwosSYGp8UJccII7YVlKDCvZrZkutbZG3niJmiUWvIOYJbsO' \
      '+gPcZ/pWY74ia62RSzn9j3/3WLV5+Nu8mrktpu9bL+OBwG55me4JHCtkiTWnWXnyvpPo7Aj3yj0DrHmaCskTshYcZdC+bmyzaid' \
      '+QF9qMtLtLUDxPifnPDdPx4QJ7O9S3AwUdYGfGzt6SWVaso+U18' \
      '+ymdOUS2B4Y54DekmUYAHFgZ47pVi8cjcPWtCoBnWXmzEncdpjDgIlRFVeU8w3nmZTkUxiuUtV87iXvekHI1azMDxZu3xUWZdWZn+UL7RlA' \
      '+RGumkrAFYQrVp4CoVyg3GajlZU4zutd3VlQKBgQD2aoXflAMWD9WFt32aE6ED9LlU7ZGzHNhw/EhzNh' \
      '+DisY4qiAERlXgZz9bJ3Rb7ljGp3WFo79uvDH7H5lIDKBjHMgp39JouqFjnWKZzH' \
      '+vz5XhvKuwCnx3jLoYsK8rLIu5sZvhkTyHMz1yCszKJsO1nR1DZsWzyG7KghK4LCNRYwKBgQDDOOopOCMg4jvO4mlEZJTFRMfwult3' \
      '+ikas5CIuOs1kR3BGXn2sciEBHG6rJ+dlrsvTJHuY9shfYZHPgp8jjG6cFbZGQoHS5W/QKn2V3LFK9+b' \
      '/+b3JSLJD3M8qb8gO70jXwxSPQginhOJ+vt6pBpIa8ysEa7WlPMc3dPWc8EHNwKBgAismUfUiwNEzWxmmCpLVJiyDbAaqM1YT5oyl05O8m8L' \
      '/IxUGMptu2op2EYaLnNqAYAEtxNcP0njoBLJ+vhZUXALvFQVB/Ad2b6K9MSbOUd0FD' \
      '+dB6IrzFPdBVQHLDNl3wlLYkRfe3T67cfM74aSNMN442XTAVSh0pyYVZZcH2YnAoGAUVw58r3LnhvLEzi26GMGwYQd08zG7CSc1tz5IpH2r' \
      'Ndy0BQ/CTokuChmAYeJ6hJ0pozB0Nla7QU0XiKUGj7kqK/C8i2GSW4N1awsaVcepN/ZDFnFN0EJ00OWIjUYS2W6OLCXIPsAlfTNbdbk0cLsl' \
      'TwgC6I+/H0NKP2mGJ0bWFcCgYEArpuAo9RSX9vkbdYkOi63zcdIXjwxJw2ddKzp1EMRuEMU6oIFaXoz1MRVsys2JB/K1WGQO9afjIvgpoI' \
      'TPEe41SVdHIHamTjjcEJXlZ6rn1oiMkqchRNLyEiW5C1+c20uvV1NwoR9Tlr+ryGJ7UXWQeZTD6mCdLOxGaN/FMvOUdQ= '
